import initSmoothScroll from './modules/scroll-suave.js';
import initScrollAnimation from './modules/scroll-animation.js';
import initTabNav from './modules/init-tab.js';
import initAccordion from './modules/accordion.js';
import initModal from './modules/modal.js';
import initTooltip from './modules/tooltip.js';
import initDropdownMenu from './modules/dropdown.js';
import initMenuMobile from './modules/menu-mobile.js';
import initAnimanNumeros from './modules/anima-numeros.js';
import initFuncionamento from './modules/funcionamento.js';

initSmoothScroll();
initScrollAnimation();
initTabNav();
initAccordion();
initModal();
initTooltip();
initDropdownMenu();
initMenuMobile();
initAnimanNumeros();
initFuncionamento();
